### ISSUE TITLE
demo site item name that have 2 more lines cannot see

### ISSUE THREAD

**Issue by Nortina** [nayunhwan/UnivColor#45]
demo site item name that have 2 more lines cannot see.

because line height equals item height. (80px same)

it's should change to flex or table cell with vertical align.

but table cell isn't easy to make item align center.

I recommend flex for make item align center.

**Comment by euntak** [comment]
[#48](https://github.com/nayunhwan/UnivColor/pull/48)
this PR using 'flexbox' for item align center!
