### ISSUE TITLE
동서울대를 검색했는데 서울대로 검색이 됩니다.

### ISSUE THREAD

**Issue by bloooi** [nayunhwan/UnivColor#68]
동서울대를 검색했는데 서울대 색이 나옵니다.
동서울대학교는 색이 추가가 안되어 있습니다.
앞에 동을 무시하고 검색이 되는 듯 합니다.

**Comment by chr0m3** [comment]
동서울대가 없어서 그런듯 합니다. 서울대가 나오는 이유는 "서울대"를 포함하는 문자열인 경우 서울대로 검색되어 그런게 아닐까 싶습니다.

**Comment by bloooi** [comment]
음.. 검색할때 전체단어 검색으로 하셔야 할 것 같습니다.
남서울대, 동서울대 같은 경우에 문제가 될것 같습니다
